#!/bin/bash
WP="wp --path=/www/wwwroot/pagcorcasino.ph --allow-root"

echo "=============================================="
echo "  Yoast SEO Full Optimization - All 5 Posts"
echo "=============================================="

# POST 1 (ID: 153)
echo ""
echo "[1/5] Optimizing: Top 10 PAGCOR Licensed Casinos (ID: 153)"

$WP post meta update 153 _yoast_wpseo_title "Top 10 PAGCOR Licensed Online Casinos in the Philippines %%sep%% %%sitename%%"
$WP post meta update 153 _yoast_wpseo_metadesc "Discover the top 10 PAGCOR licensed online casinos in the Philippines for 2026. Expert-ranked by bonuses, game variety, payout speed, and player trust. Updated March 2026."
$WP post meta update 153 _yoast_wpseo_focuskw "PAGCOR licensed online casinos"
$WP post meta update 153 _yoast_wpseo_opengraph-title "Top 10 PAGCOR Licensed Online Casinos in the Philippines (2026)"
$WP post meta update 153 _yoast_wpseo_opengraph-description "Expert-ranked list of the best PAGCOR licensed online casinos in the Philippines. Compare bonuses, payout speeds, game variety, and more. Updated March 2026."
$WP post meta update 153 _yoast_wpseo_twitter-title "Top 10 PAGCOR Licensed Online Casinos Philippines 2026"
$WP post meta update 153 _yoast_wpseo_twitter-description "Expert-ranked list of the best PAGCOR licensed online casinos. Compare bonuses, payouts, and games. Updated March 2026."
$WP post meta update 153 _yoast_wpseo_canonical "https://pagcorcasino.ph/blog/top-pagcor-licensed-online-casinos-philippines-2026"
$WP post meta update 153 _yoast_wpseo_meta-robots-noindex "0"
$WP post meta update 153 _yoast_wpseo_meta-robots-nofollow "0"
$WP post meta update 153 _yoast_wpseo_schema_article_type "BlogPosting"
$WP post meta update 153 _yoast_wpseo_schema_page_type "WebPage"
$WP post meta update 153 _yoast_wpseo_estimated-reading-time-minutes "12"
$WP post meta update 153 _yoast_wpseo_primary_category "5"
echo "  Done - Post 153"

# POST 2 (ID: 154)
echo ""
echo "[2/5] Optimizing: GCash Casino Deposits Guide (ID: 154)"

$WP post meta update 154 _yoast_wpseo_title "GCash Casino Deposits: Complete Guide to Online Casino Payments %%sep%% %%sitename%%"
$WP post meta update 154 _yoast_wpseo_metadesc "Learn how to deposit and withdraw at online casinos using GCash. Step-by-step guide with fees, limits, processing times, and troubleshooting tips for Filipino players."
$WP post meta update 154 _yoast_wpseo_focuskw "GCash casino deposit"
$WP post meta update 154 _yoast_wpseo_opengraph-title "GCash Casino Deposits: Complete Guide for Filipino Players (2026)"
$WP post meta update 154 _yoast_wpseo_opengraph-description "Step-by-step guide to depositing and withdrawing at online casinos using GCash. Includes fees, limits, processing times, and troubleshooting tips."
$WP post meta update 154 _yoast_wpseo_twitter-title "GCash Casino Deposits: Complete Guide Philippines 2026"
$WP post meta update 154 _yoast_wpseo_twitter-description "How to deposit and withdraw at online casinos using GCash. Fees, limits, processing times, and troubleshooting tips."
$WP post meta update 154 _yoast_wpseo_canonical "https://pagcorcasino.ph/blog/gcash-casino-deposits-guide-philippines"
$WP post meta update 154 _yoast_wpseo_meta-robots-noindex "0"
$WP post meta update 154 _yoast_wpseo_meta-robots-nofollow "0"
$WP post meta update 154 _yoast_wpseo_schema_article_type "BlogPosting"
$WP post meta update 154 _yoast_wpseo_schema_page_type "WebPage"
$WP post meta update 154 _yoast_wpseo_estimated-reading-time-minutes "10"
$WP post meta update 154 _yoast_wpseo_primary_category "6"
echo "  Done - Post 154"

# POST 3 (ID: 155)
echo ""
echo "[3/5] Optimizing: Best Casino Bonuses March 2026 (ID: 155)"

$WP post meta update 155 _yoast_wpseo_title "Best Online Casino Welcome Bonuses Philippines - March 2026 %%sep%% %%sitename%%"
$WP post meta update 155 _yoast_wpseo_metadesc "Compare the best online casino welcome bonuses in the Philippines for March 2026. Find the highest bonus offers, lowest wagering requirements from PAGCOR licensed casinos."
$WP post meta update 155 _yoast_wpseo_focuskw "best online casino bonuses Philippines"
$WP post meta update 155 _yoast_wpseo_opengraph-title "Best Online Casino Welcome Bonuses in the Philippines - March 2026"
$WP post meta update 155 _yoast_wpseo_opengraph-description "Compare welcome bonuses from top PAGCOR licensed casinos. Up to PHP 80,000 in bonuses with low wagering requirements. Updated March 2026."
$WP post meta update 155 _yoast_wpseo_twitter-title "Best Online Casino Bonuses Philippines - March 2026"
$WP post meta update 155 _yoast_wpseo_twitter-description "Compare the best casino welcome bonuses in the Philippines. Up to PHP 80,000 with low wagering. Updated March 2026."
$WP post meta update 155 _yoast_wpseo_canonical "https://pagcorcasino.ph/blog/best-online-casino-welcome-bonuses-philippines-march-2026"
$WP post meta update 155 _yoast_wpseo_meta-robots-noindex "0"
$WP post meta update 155 _yoast_wpseo_meta-robots-nofollow "0"
$WP post meta update 155 _yoast_wpseo_schema_article_type "BlogPosting"
$WP post meta update 155 _yoast_wpseo_schema_page_type "WebPage"
$WP post meta update 155 _yoast_wpseo_estimated-reading-time-minutes "11"
$WP post meta update 155 _yoast_wpseo_primary_category "7"
echo "  Done - Post 155"

# POST 4 (ID: 156)
echo ""
echo "[4/5] Optimizing: How to Verify PAGCOR License (ID: 156)"

$WP post meta update 156 _yoast_wpseo_title "How to Verify PAGCOR Licensed Casino - Avoid Scams 2026 %%sep%% %%sitename%%"
$WP post meta update 156 _yoast_wpseo_metadesc "Learn how to verify if an online casino is legitimately PAGCOR licensed. Spot fake casinos, avoid scams, and protect your money. Step-by-step guide for Filipino players."
$WP post meta update 156 _yoast_wpseo_focuskw "verify PAGCOR license"
$WP post meta update 156 _yoast_wpseo_opengraph-title "How to Verify if an Online Casino is PAGCOR Licensed - Avoid Scam Casinos"
$WP post meta update 156 _yoast_wpseo_opengraph-description "Step-by-step guide to verifying PAGCOR licenses. Learn to spot fake casinos, avoid scams, and protect your money as a Filipino player."
$WP post meta update 156 _yoast_wpseo_twitter-title "How to Verify PAGCOR Licensed Casino - Avoid Scams 2026"
$WP post meta update 156 _yoast_wpseo_twitter-description "Step-by-step guide to verifying PAGCOR licenses. Spot fake casinos and protect your money."
$WP post meta update 156 _yoast_wpseo_canonical "https://pagcorcasino.ph/blog/how-to-verify-pagcor-licensed-casino-avoid-scams"
$WP post meta update 156 _yoast_wpseo_meta-robots-noindex "0"
$WP post meta update 156 _yoast_wpseo_meta-robots-nofollow "0"
$WP post meta update 156 _yoast_wpseo_schema_article_type "BlogPosting"
$WP post meta update 156 _yoast_wpseo_schema_page_type "WebPage"
$WP post meta update 156 _yoast_wpseo_estimated-reading-time-minutes "9"
$WP post meta update 156 _yoast_wpseo_primary_category "6"
echo "  Done - Post 156"

# POST 5 (ID: 157)
echo ""
echo "[5/5] Optimizing: Responsible Gambling Guide (ID: 157)"

$WP post meta update 157 _yoast_wpseo_title "Responsible Gambling Philippines: Essential Tips to Stay Safe %%sep%% %%sitename%%"
$WP post meta update 157 _yoast_wpseo_metadesc "Learn how to gamble responsibly in the Philippines. Expert tips on setting limits, recognizing problem gambling signs, and finding help. Essential reading for Filipino players."
$WP post meta update 157 _yoast_wpseo_focuskw "responsible gambling Philippines"
$WP post meta update 157 _yoast_wpseo_opengraph-title "Responsible Gambling in the Philippines: Essential Tips to Stay Safe and in Control"
$WP post meta update 157 _yoast_wpseo_opengraph-description "Practical tips for gambling responsibly. Set limits, recognize warning signs, and find help resources in the Philippines. Essential guide for every casino player."
$WP post meta update 157 _yoast_wpseo_twitter-title "Responsible Gambling Philippines - Essential Safety Tips 2026"
$WP post meta update 157 _yoast_wpseo_twitter-description "Tips for gambling responsibly. Set limits, recognize warning signs, and find help resources in the Philippines."
$WP post meta update 157 _yoast_wpseo_canonical "https://pagcorcasino.ph/blog/responsible-gambling-tips-philippines-guide"
$WP post meta update 157 _yoast_wpseo_meta-robots-noindex "0"
$WP post meta update 157 _yoast_wpseo_meta-robots-nofollow "0"
$WP post meta update 157 _yoast_wpseo_schema_article_type "BlogPosting"
$WP post meta update 157 _yoast_wpseo_schema_page_type "WebPage"
$WP post meta update 157 _yoast_wpseo_estimated-reading-time-minutes "10"
$WP post meta update 157 _yoast_wpseo_primary_category "8"
echo "  Done - Post 157"

echo ""
echo "=============================================="
echo "  YOAST SEO OPTIMIZATION COMPLETE!"
echo "=============================================="
echo ""
echo "  Fields set per post:"
echo "  - SEO Title (with %%sep%% %%sitename%% vars)"
echo "  - Meta Description (under 160 chars)"
echo "  - Focus Keyphrase"
echo "  - OpenGraph Title & Description"
echo "  - Twitter Title & Description"
echo "  - Canonical URL"
echo "  - Robots: index, follow"
echo "  - Schema: BlogPosting + WebPage"
echo "  - Estimated Reading Time"
echo "  - Primary Category"
echo "=============================================="